{
 "title": "tclip",
 "description": "tclipd metrics",
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "interval", "query": "1m,5m,10m,30m,1h" },
   { "name": "job", "label": "Job", "query": "${VAR_JOB}" },
   {
    "name": "origin",
    "label": "Origin",
    "query": {
     "query": "label_values(tclip_paste_views,origin)"
    }
   }
  ]
 },
 "panels": [
  { "title": "tclip", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Pastes",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "tclip_total_pastes{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Paste Views",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 19, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(tclip_paste_views{origin=~\"$origin\"}) by (id)",
     "legendFormat": "{{id}}"
    }
   ]
  },
  {
   "title": "Go Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "process memory",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "process_resident_memory_bytes{job='$job'}",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "process_virtual_memory_bytes{job='$job'}",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "process memory deriv",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "rate(process_resident_memory_bytes{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - resident"
      },
      {
       "expr": "deriv(process_virtual_memory_bytes{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - virtual"
      }
     ]
    },
    {
     "title": "go memstats",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "go_memstats_alloc_bytes{job='$job'}",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job='$job'}[30s])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "go_memstats_stack_inuse_bytes{job='$job'}",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "go_memstats_heap_inuse_bytes{job='$job'}",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "go memstats deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "bytes" } },
     "targets": [
      {
       "expr": "deriv(go_memstats_alloc_bytes{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - bytes allocated"
      },
      {
       "expr": "rate(go_memstats_alloc_bytes_total{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - alloc rate"
      },
      {
       "expr": "deriv(go_memstats_stack_inuse_bytes{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - stack inuse"
      },
      {
       "expr": "deriv(go_memstats_heap_inuse_bytes{job='$job'}[$interval])",
       "legendFormat": "{{pod}} - heap inuse"
      }
     ]
    },
    {
     "title": "open fds",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "process_open_fds{job='$job'}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "open fds deriv",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "deriv(process_open_fds{job='$job'}[$interval])",
       "legendFormat": "{{pod}}"
      }
     ]
    },
    {
     "title": "Goroutines",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "go_goroutines{job='$job'}", "legendFormat": "{{pod}}" }
     ]
    },
    {
     "title": "GC duration quantiles",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "go_gc_duration_seconds{job='$job'}",
       "legendFormat": "{{pod}}: {{quantile}}"
      }
     ]
    }
   ]
  }
 ]
}