schema = 3

[mod]
  [mod."github.com/alexbrainman/sspi"]
    version = "v0.0.0-20231016080023-1a75b4708caa"
    hash = "sha256-Joa/NfBofK7lRlknQ5LVYD4M/dpd9xaCqsvYUBhKW0I="
  [mod."github.com/aymerick/douceur"]
    version = "v0.2.0"
    hash = "sha256-NiBX8EfOvLXNiK3pJaZX4N73YgfzdrzRXdiBFe3X3sE="
  [mod."github.com/coreos/go-iptables"]
    version = "v0.7.0"
    hash = "sha256-6zG74a2qK8NnmKGL3Cv1IGDP/MSY/PYZpEcJT8bl7JU="
  [mod."github.com/dustin/go-humanize"]
    version = "v1.0.1"
    hash = "sha256-yuvxYYngpfVkUg9yAmG99IUVmADTQA0tMbBXe0Fq0Mc="
  [mod."github.com/go-enry/go-enry/v2"]
    version = "v2.8.4"
    hash = "sha256-IzfYtlfOKsvvlej7OI2KEsWWqP3xFk/oB8scZ5OyiNA="
  [mod."github.com/go-enry/go-oniguruma"]
    version = "v1.2.1"
    hash = "sha256-DoCNyX75CuCgFnfSZs63VB4+HAIMDBgwcQglXXHRj/I="
  [mod."github.com/go-multierror/multierror"]
    version = "v1.0.2"
    hash = "sha256-uf3062IbpbpodoEXeStdLrB7klQmkp85qQPrl7sfO+Y="
  [mod."github.com/go-ole/go-ole"]
    version = "v1.3.0"
    hash = "sha256-tF8t3VcV71jQ4jbPL91BwR59AKDpUAFV1waIKzkXJu8="
  [mod."github.com/godbus/dbus/v5"]
    version = "v5.1.1-0.20230522191255-76236955d466"
    hash = "sha256-OdcyeoGQ4xWUpl21WKXkbAm8yZHMDp8giY02arupjb4="
  [mod."github.com/google/btree"]
    version = "v1.1.2"
    hash = "sha256-K7V2obq3pLM71Mg0vhhHtZ+gtaubwXPQx3xcIyZDCjM="
  [mod."github.com/google/go-cmp"]
    version = "v0.6.0"
    hash = "sha256-qgra5jze4iPGP0JSTVeY5qV5AvEnEu39LYAuUCIkMtg="
  [mod."github.com/google/uuid"]
    version = "v1.5.0"
    hash = "sha256-DasOte4xANR1VND5XEHKGhpGiyYq74TJmNrgWeIRX4U="
  [mod."github.com/gorilla/css"]
    version = "v1.0.0"
    hash = "sha256-Mmt/IqHpgrtWpbr/AKcJyf/USQTqEuv1HVivY4eHzoQ="
  [mod."github.com/insomniacslk/dhcp"]
    version = "v0.0.0-20231206064809-8c70d406f6d2"
    hash = "sha256-PHiso7HGNjCGbGdZ7TMGnSGzPDUTpvWpqAccoKPAaWM="
  [mod."github.com/josharian/native"]
    version = "v1.1.1-0.20230202152459-5c7d0dd6ab86"
    hash = "sha256-dgyrLXuM55z8FAoUjyt5TDlzim6HfphWo5wx1/DHLwE="
  [mod."github.com/jsimonetti/rtnetlink"]
    version = "v1.4.0"
    hash = "sha256-GnrF2yxgm/h1JSTN1PwI4ysTl+oY0AyWzf3Ni7LZqRM="
  [mod."github.com/kballard/go-shellquote"]
    version = "v0.0.0-20180428030007-95032a82bc51"
    hash = "sha256-AOEdKETBMUC39ln6jBJ9NYdJWp++jV5lSbjNqG3dV+c="
  [mod."github.com/klauspost/compress"]
    version = "v1.17.4"
    hash = "sha256-5E7dDtDKfL3jy7zJxHBMV57WlHZrP/OoEX5e6cOPba0="
  [mod."github.com/mattn/go-isatty"]
    version = "v0.0.20"
    hash = "sha256-qhw9hWtU5wnyFyuMbKx+7RB8ckQaFQ8D+8GKPkN3HHQ="
  [mod."github.com/mdlayher/netlink"]
    version = "v1.7.2"
    hash = "sha256-08qlkKvG1+XFY3MDx7M1jdvaDMsmF9qv5/xMNaw3snc="
  [mod."github.com/mdlayher/sdnotify"]
    version = "v1.0.0"
    hash = "sha256-O7MJt6Bam2bUoede07Z1T6EtW+kCJ+/4dJtYopZct1s="
  [mod."github.com/mdlayher/socket"]
    version = "v0.5.0"
    hash = "sha256-3zEbix66G+LQ2xAQW9XmkyubK9R+Vwnm09H5fqqLC7w="
  [mod."github.com/microcosm-cc/bluemonday"]
    version = "v1.0.25"
    hash = "sha256-/crG5s6cDrJ55nkDBwugLUpY7U+vQuHpCkKm7nnN8Zc="
  [mod."github.com/miekg/dns"]
    version = "v1.1.58"
    hash = "sha256-UGvyC1Abh2S5VaAUCV9AUuDMrCvpiWQy/UnYM9DfIB8="
  [mod."github.com/mitchellh/go-ps"]
    version = "v1.0.0"
    hash = "sha256-HzxVHNLHZpnsBuPcub0G+9jjDcDOsxM/6wifbsxf7EY="
  [mod."github.com/niklasfasching/go-org"]
    version = "v1.7.0"
    hash = "sha256-i3NdcfER5JSIJv3GIJxeNJJpOyxiyxQKPZPpK2teQt4="
  [mod."github.com/pierrec/lz4/v4"]
    version = "v4.1.21"
    hash = "sha256-u47Lm4tN2ChGDLGyR+Jpi/Mi0bOFBVT6PTpPFdu2rMU="
  [mod."github.com/remyoudompheng/bigfft"]
    version = "v0.0.0-20230129092748-24d4a6f8daec"
    hash = "sha256-vYmpyCE37eBYP/navhaLV4oX4/nu0Z/StAocLIFqrmM="
  [mod."github.com/russross/blackfriday"]
    version = "v1.6.0"
    hash = "sha256-tyqVArfv2d9sKGaG83SyZm//5QxLtGp1+qLgaz0SwAw="
  [mod."github.com/tailscale/certstore"]
    version = "v0.1.1-0.20231202035212-d3fa0460f47e"
    hash = "sha256-Q0HLTQPRsIizRqvdBBaLGoLascQiSpQm+X3NW3ytpDQ="
  [mod."github.com/tailscale/goupnp"]
    version = "v1.0.1-0.20210804011211-c64d0f06ea05"
    hash = "sha256-PRMJcYY+wjpbHkC9dQWTPErh2ID29UnFxehxmYR704I="
  [mod."github.com/tcnksm/go-httpstat"]
    version = "v0.2.0"
    hash = "sha256-bCWn8E+DcZY6+yPu07AF3hCcDZx3CFdD74qfpDIgVqI="
  [mod."github.com/u-root/uio"]
    version = "v0.0.0-20240118234441-a3c409a6018e"
    hash = "sha256-rUjQMG+HprbgHKzrIPFrQ6S3BCEyYQyUbA/D72mY8iU="
  [mod."go4.org/intern"]
    version = "v0.0.0-20210108033219-3eb7198706b2"
    hash = "sha256-JMhCNFyOOd3r3bOTyxCaejdf1kBSxfR4SG+CM6h9tTs="
  [mod."go4.org/mem"]
    version = "v0.0.0-20220726221520-4f986261bf13"
    hash = "sha256-H2Fsuvzbqp/6JKzC03XPTQTSQBcGs+B5VGsBjrQDY3c="
  [mod."go4.org/unsafe/assume-no-moving-gc"]
    version = "v0.0.0-20201222180813-1025295fd063"
    hash = "sha256-b8Kg0ufSUetDCZ3JgGtmDsvKDT1CV8pCenVd6PGaHlo="
  [mod."golang.org/x/crypto"]
    version = "v0.18.0"
    hash = "sha256-BuMVUxOIyfLo8MOhqYt+uQ8NDN6P2KdblKyfPxINzQ4="
  [mod."golang.org/x/exp"]
    version = "v0.0.0-20240119083558-1b970713d09a"
    hash = "sha256-JQ3JLywTjgboNhs12blhOkS3ty7m8sUa/zaWv1k/X28="
  [mod."golang.org/x/mod"]
    version = "v0.14.0"
    hash = "sha256-sx3hWp5l99DBfIrn821ohfoBwvaITSHMWbzPvX0btLM="
  [mod."golang.org/x/net"]
    version = "v0.20.0"
    hash = "sha256-PCttIsWSBQd6fDXL49jepszUAMLnAGAKR//5EDO3XDk="
  [mod."golang.org/x/sync"]
    version = "v0.6.0"
    hash = "sha256-LLims/wjDZtIqlYCVHREewcUOX4hwRwplEuZKPOJ/HI="
  [mod."golang.org/x/sys"]
    version = "v0.17.0"
    hash = "sha256-e0qnE+SitE02IzvnJKI4Uzpq9EOZY+zvE8Wf5b2e6Kg="
  [mod."golang.org/x/time"]
    version = "v0.5.0"
    hash = "sha256-W6RgwgdYTO3byIPOFxrP2IpAZdgaGowAaVfYby7AULU="
  [mod."golang.org/x/tools"]
    version = "v0.17.0"
    hash = "sha256-CxuHfKKtUkn3VjA7D9WQjzvV1EUbyI/xMNhb5CxO6IQ="
  [mod."golang.zx2c4.com/wireguard"]
    version = "v0.0.0-20210905140043-2ef39d47540c"
    hash = "sha256-EvQThGtWpQdSqdEo9fNZ8Zq8BAP4Fd2O3WmPt5pMS6U="
  [mod."golang.zx2c4.com/wireguard/windows"]
    version = "v0.5.3"
    hash = "sha256-wcJWS/4Fqbc+1RHSntex0zBdlHiZfzrea4QabYkNKvU="
  [mod."honnef.co/go/tools"]
    version = "v0.4.5"
    hash = "sha256-l1KrTOuH0AC+i0DW3ApypYH6PtWmHNn0uiPyaw6bfvo="
  [mod."inet.af/netaddr"]
    version = "v0.0.0-20210721214506-ce7a8ad02cc1"
    hash = "sha256-RMhUs9rTSkPsaLDlJfhRzHxJMxfoDs6asBxxhBixqhI="
  [mod."inet.af/netstack"]
    version = "v0.0.0-20210622165351-29b14ebc044e"
    hash = "sha256-cToEQOekd/Z8PQyTTL3vazA2/Fg9VTZ/DPJoizWuhrg="
  [mod."lukechampine.com/uint128"]
    version = "v1.2.0"
    hash = "sha256-gwpTC3V+1pxjzxZvCnum+qpaGD84WtHncywddTSPye4="
  [mod."modernc.org/cc/v3"]
    version = "v3.40.0"
    hash = "sha256-s7KmY6n9S4JfP03mJ58OYJJYLLgL7iBcTf+uAqxR3rM="
  [mod."modernc.org/ccgo/v3"]
    version = "v3.16.13"
    hash = "sha256-4bBUzkL+uXQ4Pe9BZjCj4PuJ8pR+8lC6+aQhC1z8iQw="
  [mod."modernc.org/libc"]
    version = "v1.24.1"
    hash = "sha256-ncVRe3Mx5agBpEoAlEsZkWaVTKulHSZB9DMrWs+iisw="
  [mod."modernc.org/mathutil"]
    version = "v1.5.0"
    hash = "sha256-5xM9HjjHf9sB0vLfN53PdGpT0qPF1+KI1/lgN0/4LQo="
  [mod."modernc.org/memory"]
    version = "v1.6.0"
    hash = "sha256-XxRCHqhE+oD5UV0PQpwGpvqMUfOX9d59SRPcBwOaNGk="
  [mod."modernc.org/opt"]
    version = "v0.1.3"
    hash = "sha256-7C/odVzq+jp8aP6zbwH2cp8r4fxZ3nfQ4Cz3p9cshHE="
  [mod."modernc.org/sqlite"]
    version = "v1.25.0"
    hash = "sha256-+EghwLCPWp9xlr3JbU4izb5jXjVyAkSpsiPvQxKYxtA="
  [mod."modernc.org/strutil"]
    version = "v1.1.3"
    hash = "sha256-uEGJcwaeeN7cy62v06HoRdHB1p14McdlPID8QGJQd4k="
  [mod."modernc.org/token"]
    version = "v1.0.1"
    hash = "sha256-lTSZX8nrb5hDZqOnRuFmI4VIaco3qwwWe28z24vohyo="
  [mod."tailscale.com"]
    version = "v1.16.2"
    hash = "sha256-fMRki482g5EstaLfhutmmfTQlAG1g2Wt5uHCSmS8Jc0="
